- hosts: cluster
  become: yes
  tasks:

    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: yes

    - name: Create app directoty
      file:
        path: /opt/parking-segmentation
        state: directory

    - name: Copy docker-compose.yml
      copy:
         src: ../docker-compose.yml
         dest: /opt/parking-segmentation/docker-compose.yml

    - name: Log into GitHub Container Registry
      docker_login:
        registry_url: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"
        reauthorize: yes

    - name: Start service
      command: docker compose up -d
      args:
         chdir: /opt/parking-segmentation